### ISSUE TITLE
Error when using 4.0.0rc7 version

### ISSUE THREAD

**Issue by andrewsiemer** [akavbathen/pytest_html_merger#5]
Hi, I am trying to merge a few reports together and am running into the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pytest_html_merger/main.py", line 249, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/pytest_html_merger/main.py", line 245, in main
    merge_html_files(args.input, args.output)
  File "/usr/local/lib/python3.7/dist-packages/pytest_html_merger/main.py", line 113, in merge_html_files
    fp.string = f"{test_count} tests ran in {dur} seconds"
AttributeError: 'NoneType' object has no attribute 'string'
```
I believe this is due to the fact that my pytest version was "4.0.0rc7" which makes `if html_ver >= version.parse("4.0.0"):` evaluate to False causing `fp` to remain None on return.

**Comment by progovoy** [comment]
0.0.10
